#!/usr/bin/env sh
set -eu

EnvFile="${1:-.env}"

GenerateSecret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
    return
  fi

  if command -v node >/dev/null 2>&1; then
    node -e "process.stdout.write(require('crypto').randomBytes(32).toString('hex'))"
    return
  fi

  date +%s | sha256sum | cut -d " " -f 1
}

UrlEncode() {
  Value="$1"

  if command -v node >/dev/null 2>&1; then
    node -e "process.stdout.write(encodeURIComponent(process.argv[1]))" "${Value}"
    return
  fi

  printf '%s' "${Value}"
}

GenerateComposeProjectName() {
  ProjectPath="$(CDPATH= cd -- "$(dirname -- "${EnvFile}")" && pwd -P)"
  BaseName="$(basename "${ProjectPath}" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g;s/^-*//;s/-*$//;s/--*/-/g')"
  HashValue="$(printf '%s' "${ProjectPath}" | cksum | awk '{ print $1 }')"

  if [ -z "${BaseName}" ]; then
    BaseName="hyperbot"
  fi

  printf 'hyperbot-%s-%s' "${BaseName}" "${HashValue}"
}

ReadEnvValue() {
  Key="$1"

  if [ ! -f "${EnvFile}" ]; then
    return
  fi

  grep -E "^${Key}=" "${EnvFile}" | tail -n 1 | cut -d "=" -f 2- | sed 's/^"//;s/"$//'
}

SetEnvKey() {
  Key="$1"
  Value="$2"

  if grep -q -E "^${Key}=" "${EnvFile}"; then
    TempFile="${EnvFile}.tmp"
    awk -v Key="${Key}" -v Value="${Value}" '
      BEGIN { Updated = 0 }
      $0 ~ "^" Key "=" {
        if (Updated == 0) {
          print Key "=\"" Value "\""
          Updated = 1
        }
        next
      }
      { print }
    ' "${EnvFile}" > "${TempFile}"
    mv "${TempFile}" "${EnvFile}"
  else
    printf '%s="%s"\n' "${Key}" "${Value}" >> "${EnvFile}"
  fi
}

EnsureEnvKey() {
  Key="$1"
  Value="$2"
  CurrentValue="$(ReadEnvValue "${Key}")"

  if [ -z "${CurrentValue}" ]; then
    SetEnvKey "${Key}" "${Value}"
  fi
}

if [ ! -f "${EnvFile}" ]; then
  {
    echo "# Generated by scripts/EnsureEnv.sh"
    echo "# Keep this file private. It contains database and Redis passwords."
  } > "${EnvFile}"
fi

PostgresPassword="$(ReadEnvValue POSTGRES_PASSWORD)"
RedisPassword="$(ReadEnvValue REDIS_PASSWORD)"
ComposeProjectName="$(ReadEnvValue COMPOSE_PROJECT_NAME)"
AppHostPort="$(ReadEnvValue APP_HOST_PORT)"

if [ -z "${PostgresPassword}" ] || [ "${PostgresPassword}" = "change-me" ]; then
  PostgresPassword="$(GenerateSecret)"
fi

if [ -z "${RedisPassword}" ] || [ "${RedisPassword}" = "change-me" ]; then
  RedisPassword="$(GenerateSecret)"
fi

if [ -z "${ComposeProjectName}" ]; then
  ComposeProjectName="$(GenerateComposeProjectName)"
fi

if [ "${AppHostPort}" = "3000" ]; then
  AppHostPort=""
fi

SetEnvKey COMPOSE_PROJECT_NAME "${ComposeProjectName}"
SetEnvKey POSTGRES_PASSWORD "${PostgresPassword}"
SetEnvKey REDIS_PASSWORD "${RedisPassword}"
SetEnvKey POSTGRES_PASSWORD_URL_ENCODED "$(UrlEncode "${PostgresPassword}")"
SetEnvKey REDIS_PASSWORD_URL_ENCODED "$(UrlEncode "${RedisPassword}")"
SetEnvKey APP_HOST_PORT "${AppHostPort}"
EnsureEnvKey SUPER_ADMIN_IDS ""
EnsureEnvKey PUBLIC_REGISTRATION_ENABLED "true"
EnsureEnvKey PLUGIN_DIRECTORY "Plugins"
EnsureEnvKey NEXT_PUBLIC_APP_URL "http://localhost:3000"
EnsureEnvKey ENABLE_MESSAGE_EVENTS "true"
EnsureEnvKey FOLLOW_LOGS "true"
EnsureEnvKey TEMPVOICE_YOUTUBE_COOKIES_PATH ""
EnsureEnvKey YOUTUBE_COOKIES_PATH ""
EnsureEnvKey APP_HOST_BIND "127.0.0.1"
EnsureEnvKey DATABASE_HOST_BIND "127.0.0.1"
