param(
  [string]$EnvFile = ".env"
)

function New-HyperBotSecret {
  $Bytes = New-Object byte[] 32
  [System.Security.Cryptography.RandomNumberGenerator]::Fill($Bytes)
  return ($Bytes | ForEach-Object { $_.ToString("x2") }) -join ""
}

function Get-HyperBotEnvValue {
  param([string]$Key)

  if (-not (Test-Path $EnvFile)) {
    return ""
  }

  $Line = Get-Content $EnvFile | Where-Object { $_ -match "^$([regex]::Escape($Key))=" } | Select-Object -Last 1

  if (-not $Line) {
    return ""
  }

  return ($Line.Substring($Key.Length + 1)).Trim('"')
}

function Add-HyperBotEnvValue {
  param(
    [string]$Key,
    [string]$Value
  )

  $CurrentValue = Get-HyperBotEnvValue $Key

  if ($CurrentValue) {
    return
  }

  Add-Content -Path $EnvFile -Value "$Key=`"$Value`""
}

function ConvertTo-HyperBotUrlEncoded {
  param([string]$Value)

  return [System.Uri]::EscapeDataString($Value)
}

if (-not (Test-Path $EnvFile)) {
  Set-Content -Path $EnvFile -Value @(
    "# Generated by scripts/EnsureEnv.ps1",
    "# Keep this file private. It contains database and Redis passwords."
  )
}

$PostgresPassword = Get-HyperBotEnvValue "POSTGRES_PASSWORD"
$RedisPassword = Get-HyperBotEnvValue "REDIS_PASSWORD"

if (-not $PostgresPassword -or $PostgresPassword -eq "change-me") {
  $PostgresPassword = New-HyperBotSecret
}

if (-not $RedisPassword -or $RedisPassword -eq "change-me") {
  $RedisPassword = New-HyperBotSecret
}

Add-HyperBotEnvValue "POSTGRES_PASSWORD" $PostgresPassword
Add-HyperBotEnvValue "REDIS_PASSWORD" $RedisPassword
Add-HyperBotEnvValue "POSTGRES_PASSWORD_URL_ENCODED" (ConvertTo-HyperBotUrlEncoded $PostgresPassword)
Add-HyperBotEnvValue "REDIS_PASSWORD_URL_ENCODED" (ConvertTo-HyperBotUrlEncoded $RedisPassword)
Add-HyperBotEnvValue "DISCORD_TOKEN" ""
Add-HyperBotEnvValue "DISCORD_CLIENT_ID" ""
Add-HyperBotEnvValue "DISCORD_GUILD_ID" ""
Add-HyperBotEnvValue "SUPER_ADMIN_IDS" ""
Add-HyperBotEnvValue "PUBLIC_REGISTRATION_ENABLED" "true"
Add-HyperBotEnvValue "PLUGIN_DIRECTORY" "Plugins"
Add-HyperBotEnvValue "NEXT_PUBLIC_APP_URL" "http://localhost:3000"
Add-HyperBotEnvValue "ENABLE_MESSAGE_EVENTS" "false"
Add-HyperBotEnvValue "FOLLOW_LOGS" "true"
