#!/usr/bin/env sh
set -eu

EnvFile="${1:-.env}"

GenerateSecret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
    return
  fi

  if command -v node >/dev/null 2>&1; then
    node -e "process.stdout.write(require('crypto').randomBytes(32).toString('hex'))"
    return
  fi

  date +%s | sha256sum | cut -d " " -f 1
}

UrlEncode() {
  Value="$1"

  if command -v node >/dev/null 2>&1; then
    node -e "process.stdout.write(encodeURIComponent(process.argv[1]))" "${Value}"
    return
  fi

  printf '%s' "${Value}"
}

ReadEnvValue() {
  Key="$1"

  if [ ! -f "${EnvFile}" ]; then
    return
  fi

  grep -E "^${Key}=" "${EnvFile}" | tail -n 1 | cut -d "=" -f 2- | sed 's/^"//;s/"$//'
}

EnsureEnvKey() {
  Key="$1"
  Value="$2"
  CurrentValue="$(ReadEnvValue "${Key}")"

  if [ -n "${CurrentValue}" ]; then
    return
  fi

  printf '%s="%s"\n' "${Key}" "${Value}" >> "${EnvFile}"
}

if [ ! -f "${EnvFile}" ]; then
  {
    echo "# Generated by scripts/EnsureEnv.sh"
    echo "# Keep this file private. It contains database and Redis passwords."
  } > "${EnvFile}"
fi

PostgresPassword="$(ReadEnvValue POSTGRES_PASSWORD)"
RedisPassword="$(ReadEnvValue REDIS_PASSWORD)"

if [ -z "${PostgresPassword}" ] || [ "${PostgresPassword}" = "change-me" ]; then
  PostgresPassword="$(GenerateSecret)"
fi

if [ -z "${RedisPassword}" ] || [ "${RedisPassword}" = "change-me" ]; then
  RedisPassword="$(GenerateSecret)"
fi

EnsureEnvKey POSTGRES_PASSWORD "${PostgresPassword}"
EnsureEnvKey REDIS_PASSWORD "${RedisPassword}"
EnsureEnvKey POSTGRES_PASSWORD_URL_ENCODED "$(UrlEncode "${PostgresPassword}")"
EnsureEnvKey REDIS_PASSWORD_URL_ENCODED "$(UrlEncode "${RedisPassword}")"
EnsureEnvKey DISCORD_TOKEN ""
EnsureEnvKey DISCORD_CLIENT_ID ""
EnsureEnvKey DISCORD_GUILD_ID ""
EnsureEnvKey SUPER_ADMIN_IDS ""
EnsureEnvKey PUBLIC_REGISTRATION_ENABLED "true"
EnsureEnvKey PLUGIN_DIRECTORY "Plugins"
EnsureEnvKey NEXT_PUBLIC_APP_URL "http://localhost:3000"
EnsureEnvKey ENABLE_MESSAGE_EVENTS "false"
EnsureEnvKey FOLLOW_LOGS "true"
