param(
  [string]$EnvFile = ".env"
)

function New-HyperBotSecret {
  $Bytes = New-Object byte[] 32
  [System.Security.Cryptography.RandomNumberGenerator]::Fill($Bytes)
  return ($Bytes | ForEach-Object { $_.ToString("x2") }) -join ""
}

function Get-HyperBotEnvValue {
  param([string]$Key)

  if (-not (Test-Path $EnvFile)) {
    return ""
  }

  $Line = Get-Content $EnvFile | Where-Object { $_ -match "^$([regex]::Escape($Key))=" } | Select-Object -Last 1

  if (-not $Line) {
    return ""
  }

  return ($Line.Substring($Key.Length + 1)).Trim('"')
}

function Set-HyperBotEnvValue {
  param(
    [string]$Key,
    [string]$Value
  )

  if (Test-Path $EnvFile) {
    $Lines = Get-Content $EnvFile
    $Updated = $false
    $NextLines = foreach ($Line in $Lines) {
      if ($Line -match "^$([regex]::Escape($Key))=") {
        if (-not $Updated) {
          "$Key=`"$Value`""
          $Updated = $true
        }
      } else {
        $Line
      }
    }

    if ($Updated) {
      Set-Content -Path $EnvFile -Value $NextLines
      return
    }
  }

  Add-Content -Path $EnvFile -Value "$Key=`"$Value`""
}

function Add-HyperBotEnvValue {
  param(
    [string]$Key,
    [string]$Value
  )

  if (Get-HyperBotEnvValue $Key) {
    return
  }

  Set-HyperBotEnvValue $Key $Value
}

function ConvertTo-HyperBotUrlEncoded {
  param([string]$Value)

  return [System.Uri]::EscapeDataString($Value)
}

function New-HyperBotComposeProjectName {
  $ProjectPath = (Resolve-Path (Split-Path -Parent $EnvFile)).Path
  $BaseName = (Split-Path -Leaf $ProjectPath).ToLowerInvariant() -replace "[^a-z0-9]", "-"
  $BaseName = ($BaseName -replace "-+", "-").Trim("-")

  if (-not $BaseName) {
    $BaseName = "hyperbot"
  }

  $Bytes = [System.Text.Encoding]::UTF8.GetBytes($ProjectPath)
  $HashBytes = [System.Security.Cryptography.SHA256]::HashData($Bytes)
  $Hash = (($HashBytes | Select-Object -First 4) | ForEach-Object { $_.ToString("x2") }) -join ""
  return "hyperbot-$BaseName-$Hash"
}

if (-not (Test-Path $EnvFile)) {
  Set-Content -Path $EnvFile -Value @(
    "# Generated by scripts/EnsureEnv.ps1",
    "# Keep this file private. It contains database and Redis passwords."
  )
}

$PostgresPassword = Get-HyperBotEnvValue "POSTGRES_PASSWORD"
$RedisPassword = Get-HyperBotEnvValue "REDIS_PASSWORD"
$ComposeProjectName = Get-HyperBotEnvValue "COMPOSE_PROJECT_NAME"
$AppHostPort = Get-HyperBotEnvValue "APP_HOST_PORT"

if (-not $PostgresPassword -or $PostgresPassword -eq "change-me") {
  $PostgresPassword = New-HyperBotSecret
}

if (-not $RedisPassword -or $RedisPassword -eq "change-me") {
  $RedisPassword = New-HyperBotSecret
}

if (-not $ComposeProjectName) {
  $ComposeProjectName = New-HyperBotComposeProjectName
}

if ($AppHostPort -eq "3000") {
  $AppHostPort = ""
}

Set-HyperBotEnvValue "COMPOSE_PROJECT_NAME" $ComposeProjectName
Set-HyperBotEnvValue "POSTGRES_PASSWORD" $PostgresPassword
Set-HyperBotEnvValue "REDIS_PASSWORD" $RedisPassword
Set-HyperBotEnvValue "POSTGRES_PASSWORD_URL_ENCODED" (ConvertTo-HyperBotUrlEncoded $PostgresPassword)
Set-HyperBotEnvValue "REDIS_PASSWORD_URL_ENCODED" (ConvertTo-HyperBotUrlEncoded $RedisPassword)
Set-HyperBotEnvValue "APP_HOST_PORT" $AppHostPort
Add-HyperBotEnvValue "SUPER_ADMIN_IDS" ""
Add-HyperBotEnvValue "PUBLIC_REGISTRATION_ENABLED" "true"
Add-HyperBotEnvValue "PLUGIN_DIRECTORY" "Plugins"
Add-HyperBotEnvValue "NEXT_PUBLIC_APP_URL" "http://localhost:3000"
Add-HyperBotEnvValue "ENABLE_MESSAGE_EVENTS" "true"
Add-HyperBotEnvValue "FOLLOW_LOGS" "true"
Add-HyperBotEnvValue "TEMPVOICE_YOUTUBE_COOKIES_PATH" ""
Add-HyperBotEnvValue "YOUTUBE_COOKIES_PATH" ""
Add-HyperBotEnvValue "TENOR_API_KEY" ""
Add-HyperBotEnvValue "APP_HOST_BIND" "127.0.0.1"
Add-HyperBotEnvValue "DATABASE_HOST_BIND" "127.0.0.1"
