#!/usr/bin/env python3
from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import os
import secrets
import shutil
import socket
import subprocess
import sys
import time
import urllib.parse
import zipfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ENV_FILE = ROOT / ".env"
REPOSITORY_URL = "https://github.com/Totgocpro/HyperBot.git"
UPDATE_BRANCH_CANDIDATES = ("master", "main")
DEFAULT_PORT = 3000
UPDATE_SOURCE_BACKUP_EXCLUDES = {
    ".git",
    ".hyperbot-cli-venv",
    ".next",
    "Backups",
    "dist",
    "Exports",
    "node_modules",
    "tsconfig.tsbuildinfo",
}


class Ui:
    def __init__(self) -> None:
        self.color = sys.stdout.isatty() and os.environ.get("NO_COLOR") is None

    def c(self, text: str, code: str) -> str:
        if not self.color:
            return text
        return f"\033[{code}m{text}\033[0m"

    def title(self, text: str) -> None:
        line = "═" * max(12, len(text) + 4)
        print(self.c(f"\n╔{line}╗", "36;1"))
        print(self.c(f"║  {text}  ║", "36;1"))
        print(self.c(f"╚{line}╝", "36;1"))

    def step(self, text: str) -> None:
        print(self.c(f"\n▸ {text}", "34;1"))

    def ok(self, text: str) -> None:
        print(self.c(f"✓ {text}", "32;1"))

    def warn(self, text: str) -> None:
        print(self.c(f"! {text}", "33;1"))

    def error(self, text: str) -> None:
        print(self.c(f"✗ {text}", "31;1"), file=sys.stderr)

    def command(self, command: list[str]) -> None:
        print(self.c("$ " + " ".join(command), "2"))


ui = Ui()


class HyperBotError(RuntimeError):
    pass


def run(
    command: list[str],
    *,
    check: bool = True,
    capture: bool = False,
    env: dict[str, str] | None = None,
    input_text: str | None = None,
    stdout_file: Path | None = None,
) -> subprocess.CompletedProcess[str]:
    ui.command(command)
    stdout = subprocess.PIPE if capture else None
    if stdout_file is not None:
        stdout_handle = stdout_file.open("wb")
    else:
        stdout_handle = None

    try:
        completed = subprocess.run(
            command,
            cwd=ROOT,
            env=env,
            input=input_text,
            text=True if stdout_handle is None else False,
            stdout=stdout_handle if stdout_handle is not None else stdout,
            stderr=subprocess.STDOUT if capture else None,
            check=False,
        )
    finally:
        if stdout_handle is not None:
            stdout_handle.close()

    if check and completed.returncode != 0:
        output = ""
        if capture and completed.stdout:
            output = f"\n{completed.stdout.strip()}"
        raise HyperBotError(f"Command failed: {' '.join(command)}{output}")

    return completed


def require_command(name: str) -> None:
    if shutil.which(name) is None:
        raise HyperBotError(f"Missing command: {name}. Install it, then run HyperBot again.")


def docker_compose(*args: str, **kwargs: object) -> subprocess.CompletedProcess[str]:
    return run(["docker", "compose", *args], **kwargs)  # type: ignore[arg-type]


def read_env(path: Path = ENV_FILE) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip().strip('"').strip("'")
    return values


def write_env(values: dict[str, str], path: Path = ENV_FILE) -> None:
    existing = path.read_text(encoding="utf-8").splitlines() if path.exists() else []
    seen: set[str] = set()
    next_lines: list[str] = []

    if not existing:
        next_lines.extend(
            [
                "# Generated by HyperBot CLI",
                "# Keep this file private. It contains database and Redis passwords.",
            ]
        )

    for line in existing:
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            next_lines.append(line)
            continue

        key = stripped.split("=", 1)[0].strip()
        if key in values:
            next_lines.append(f'{key}="{values[key]}"')
            seen.add(key)
        else:
            next_lines.append(line)

    for key in values:
        if key not in seen:
            next_lines.append(f'{key}="{values[key]}"')

    path.write_text("\n".join(next_lines) + "\n", encoding="utf-8")


def compose_project_name() -> str:
    base = "".join(char.lower() if char.isalnum() else "-" for char in ROOT.name).strip("-")
    base = "-".join(part for part in base.split("-") if part) or "hyperbot"
    digest = hashlib.sha256(str(ROOT).encode("utf-8")).hexdigest()[:8]
    return f"hyperbot-{base}-{digest}"


def port_is_free(port: int, bind_host: str = "127.0.0.1") -> bool:
    host = "127.0.0.1" if bind_host in {"", "0.0.0.0"} else bind_host
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        try:
            sock.bind((host, port))
        except OSError:
            return False
    return True


def find_free_port(bind_host: str = "127.0.0.1") -> int:
    host = "127.0.0.1" if bind_host in {"", "0.0.0.0"} else bind_host
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.bind((host, 0))
        return int(sock.getsockname()[1])


def normalize_port(value: str | int | None) -> int | None:
    if value in {None, ""}:
        return None
    try:
        port = int(value)
    except (TypeError, ValueError) as exc:
        raise HyperBotError(f"Invalid port: {value}") from exc
    if port < 1 or port > 65535:
        raise HyperBotError("The port must be between 1 and 65535.")
    return port


def choose_dashboard_port(
    values: dict[str, str],
    *,
    requested_port: int | None = None,
    prefer_default: bool = True,
    exact: bool = False,
) -> int:
    bind_host = values.get("APP_HOST_BIND") or "127.0.0.1"

    if requested_port is not None:
        if exact and not port_is_free(requested_port, bind_host):
            raise HyperBotError(f"Port {requested_port} is already in use.")
        values["APP_HOST_PORT"] = str(requested_port)
        return requested_port

    current_port = normalize_port(values.get("APP_HOST_PORT"))
    if current_port is not None:
        return current_port

    if prefer_default and port_is_free(DEFAULT_PORT, bind_host):
        values["APP_HOST_PORT"] = str(DEFAULT_PORT)
        return DEFAULT_PORT

    fallback = find_free_port(bind_host)
    values["APP_HOST_PORT"] = str(fallback)
    ui.warn(f"Port {DEFAULT_PORT} is already in use. HyperBot will use port {fallback}.")
    return fallback


def ensure_env(
    *,
    requested_port: int | None = None,
    exact_port: bool = False,
    prefer_default: bool = True,
    recheck_default_port: bool = False,
) -> dict[str, str]:
    values = read_env()

    values.setdefault("COMPOSE_PROJECT_NAME", compose_project_name())
    if not values.get("COMPOSE_PROJECT_NAME"):
        values["COMPOSE_PROJECT_NAME"] = compose_project_name()

    if not values.get("POSTGRES_PASSWORD") or values.get("POSTGRES_PASSWORD") == "change-me":
        values["POSTGRES_PASSWORD"] = secrets.token_hex(32)
    if not values.get("REDIS_PASSWORD") or values.get("REDIS_PASSWORD") == "change-me":
        values["REDIS_PASSWORD"] = secrets.token_hex(32)

    values["POSTGRES_PASSWORD_URL_ENCODED"] = urllib.parse.quote(values["POSTGRES_PASSWORD"], safe="")
    values["REDIS_PASSWORD_URL_ENCODED"] = urllib.parse.quote(values["REDIS_PASSWORD"], safe="")

    defaults = {
        "SUPER_ADMIN_IDS": "",
        "PUBLIC_REGISTRATION_ENABLED": "true",
        "PLUGIN_DIRECTORY": "Plugins",
        "ENABLE_MESSAGE_EVENTS": "true",
        "FOLLOW_LOGS": "true",
        "TEMPVOICE_YOUTUBE_COOKIES_PATH": "",
        "YOUTUBE_COOKIES_PATH": "",
        "TENOR_API_KEY": "",
        "APP_HOST_BIND": "127.0.0.1",
        "DATABASE_HOST_BIND": "127.0.0.1",
    }
    for key, value in defaults.items():
        values.setdefault(key, value)

    if recheck_default_port and requested_port is None and values.get("APP_HOST_PORT") == str(DEFAULT_PORT):
        values["APP_HOST_PORT"] = ""

    port = choose_dashboard_port(
        values,
        requested_port=requested_port,
        prefer_default=prefer_default,
        exact=exact_port,
    )
    if not values.get("NEXT_PUBLIC_APP_URL") or "localhost:" in values.get("NEXT_PUBLIC_APP_URL", ""):
        values["NEXT_PUBLIC_APP_URL"] = f"http://localhost:{port}"

    write_env(values)
    return values


def build_runtime_env(values: dict[str, str]) -> dict[str, str]:
    env = os.environ.copy()
    env.update(values)
    env["NEXT_TELEMETRY_DISABLED"] = values.get("NEXT_TELEMETRY_DISABLED", "1")
    env["NODE_OPTIONS"] = (values.get("NODE_OPTIONS", "") + " --no-deprecation").strip()
    return env


def compose_port(service: str, internal_port: int) -> str:
    completed = docker_compose("port", service, str(internal_port), capture=True)
    output = (completed.stdout or "").strip().splitlines()
    if not output:
        return ""
    return output[-1].rsplit(":", 1)[-1]


def wait_for_postgresql(timeout_seconds: int = 120) -> None:
    ui.step("Waiting for PostgreSQL")
    deadline = time.time() + timeout_seconds
    while time.time() < deadline:
        completed = docker_compose(
            "exec",
            "-T",
            "postgresql",
            "pg_isready",
            "-U",
            "hyperbot",
            "-d",
            "postgres",
            check=False,
            capture=True,
        )
        if completed.returncode == 0:
            ui.ok("PostgreSQL is ready.")
            return
        time.sleep(1)
    raise HyperBotError("PostgreSQL did not respond in time.")


def sync_postgresql_password(values: dict[str, str]) -> None:
    ui.step("Synchronizing the PostgreSQL password")
    docker_compose(
        "exec",
        "-T",
        "postgresql",
        "psql",
        "-U",
        "hyperbot",
        "-d",
        "postgres",
        "-v",
        "ON_ERROR_STOP=1",
        "-v",
        f"password={values['POSTGRES_PASSWORD']}",
        input_text="ALTER USER hyperbot WITH PASSWORD :'password';\n",
    )


def ensure_database_exists() -> None:
    ui.step("Checking the HyperBot database")
    docker_compose(
        "exec",
        "-T",
        "postgresql",
        "psql",
        "-U",
        "hyperbot",
        "-d",
        "postgres",
        "-v",
        "ON_ERROR_STOP=1",
        input_text=(
            "SELECT 'CREATE DATABASE hyperbot OWNER hyperbot'\n"
            "WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'hyperbot')\n"
            "\\gexec\n"
        ),
    )


def backup_database() -> Path | None:
    backup_dir = ROOT / "Backups" / "PostgreSQL"
    backup_dir.mkdir(parents=True, exist_ok=True)

    exists = docker_compose(
        "exec",
        "-T",
        "postgresql",
        "psql",
        "-U",
        "hyperbot",
        "-d",
        "postgres",
        "-tAc",
        "SELECT 1 FROM pg_database WHERE datname = 'hyperbot';",
        check=False,
        capture=True,
    )
    if "1" not in (exists.stdout or ""):
        ui.warn("No existing hyperbot database was found to back up.")
        return None

    timestamp = dt.datetime.now().strftime("%Y%m%d-%H%M%S")
    backup_path = backup_dir / f"hyperbot-{timestamp}.dump"
    latest_path = backup_dir / "hyperbot-latest.dump"

    ui.step(f"Saving PostgreSQL backup to {backup_path}")
    docker_compose(
        "exec",
        "-T",
        "postgresql",
        "pg_dump",
        "-U",
        "hyperbot",
        "-d",
        "hyperbot",
        "-Fc",
        stdout_file=backup_path,
    )
    shutil.copy2(backup_path, latest_path)
    return backup_path


def print_status(values: dict[str, str]) -> None:
    app_port = compose_port("application", 3000) or values.get("APP_HOST_PORT", str(DEFAULT_PORT))
    ui.ok(f"Web dashboard: http://127.0.0.1:{app_port}")
    docker_compose("ps", check=False)


def command_start(args: argparse.Namespace) -> None:
    ui.title("HyperBot - Start")
    require_command("docker")
    requested_port = normalize_port(args.port)
    values = ensure_env(requested_port=requested_port, exact_port=args.exact_port)
    env = build_runtime_env(values)

    ui.step("Starting PostgreSQL and Redis")
    docker_compose("up", "-d", "--remove-orphans", "postgresql", "redis", env=env)
    ui.ok(f"PostgreSQL local: {compose_port('postgresql', 5432) or 'auto'}")
    ui.ok(f"Redis local: {compose_port('redis', 6379) or 'auto'}")

    wait_for_postgresql()
    sync_postgresql_password(values)
    if not args.no_backup:
        backup_database()
    ensure_database_exists()

    ui.step("Building the Docker image")
    docker_compose("build", "application", env=env)

    ui.step("Synchronizing Prisma")
    docker_compose("run", "--rm", "application", "npx", "prisma", "db", "push", env=env)

    ui.step("Starting the application")
    docker_compose("up", "-d", "--remove-orphans", "postgresql", "redis", "application", env=env)
    print_status(values)

    if args.logs:
        command_logs(argparse.Namespace(follow=True))


def command_create(args: argparse.Namespace) -> None:
    ui.title("HyperBot - Instance Creation")
    requested_port = normalize_port(args.port) if args.port else None
    values = ensure_env(
        requested_port=requested_port,
        exact_port=bool(requested_port),
        recheck_default_port=True,
    )
    ui.ok(f"Instance configured in {ROOT}")
    ui.ok(f"Web port configured: {values.get('APP_HOST_PORT')}")

    if args.no_start:
        return

    start_args = argparse.Namespace(
        port=values.get("APP_HOST_PORT"),
        exact_port=False,
        no_backup=True,
        logs=args.logs,
    )
    command_start(start_args)


def command_stop(args: argparse.Namespace) -> None:
    ui.title("HyperBot - Stop")
    require_command("docker")
    if args.down:
        docker_compose("down")
        ui.ok("Containers stopped. Docker volumes were kept.")
    else:
        docker_compose("stop", "application", "redis", "postgresql", check=False)
        ui.ok("HyperBot is stopped.")


def command_status(_: argparse.Namespace) -> None:
    ui.title("HyperBot - Status")
    require_command("docker")
    values = ensure_env(prefer_default=False)
    print_status(values)


def command_logs(args: argparse.Namespace) -> None:
    ui.title("HyperBot - Logs")
    require_command("docker")
    command = ["logs"]
    if args.follow:
        command.append("-f")
    command.append("application")
    docker_compose(*command, check=False)


def command_configure(args: argparse.Namespace) -> None:
    ui.title("HyperBot - Configuration")
    values = ensure_env(prefer_default=True)

    if args.port:
        port = normalize_port(args.port)
        choose_dashboard_port(values, requested_port=port, exact=True)
    if args.host_bind:
        values["APP_HOST_BIND"] = args.host_bind
    if args.super_admins is not None:
        values["SUPER_ADMIN_IDS"] = args.super_admins
    if args.registration is not None:
        values["PUBLIC_REGISTRATION_ENABLED"] = "true" if args.registration else "false"
    if args.tenor_key is not None:
        values["TENOR_API_KEY"] = args.tenor_key

    if args.interactive:
        current_port = values.get("APP_HOST_PORT") or str(DEFAULT_PORT)
        entered_port = input(f"Web port [{current_port}]: ").strip()
        if entered_port:
            choose_dashboard_port(values, requested_port=normalize_port(entered_port), exact=True)

        current_bind = values.get("APP_HOST_BIND") or "127.0.0.1"
        entered_bind = input(f"Web bind address [{current_bind}]: ").strip()
        if entered_bind:
            values["APP_HOST_BIND"] = entered_bind

        current_admins = values.get("SUPER_ADMIN_IDS", "")
        entered_admins = input(f"Discord super-admin IDs, comma-separated [{current_admins}]: ").strip()
        if entered_admins:
            values["SUPER_ADMIN_IDS"] = entered_admins

        current_registration = values.get("PUBLIC_REGISTRATION_ENABLED", "true")
        entered_registration = input(f"Public registration true/false [{current_registration}]: ").strip().lower()
        if entered_registration in {"true", "false"}:
            values["PUBLIC_REGISTRATION_ENABLED"] = entered_registration

    port = values.get("APP_HOST_PORT", str(DEFAULT_PORT))
    values["NEXT_PUBLIC_APP_URL"] = f"http://localhost:{port}"
    write_env(values)
    ui.ok(f"Configuration saved to {ENV_FILE}")
    ui.ok(f"Web dashboard: http://127.0.0.1:{port}")


def add_path_to_zip(archive: zipfile.ZipFile, path: Path, arc_prefix: str = "") -> None:
    if not path.exists():
        return
    if path.is_file():
        archive.write(path, f"{arc_prefix}{path.name}")
        return
    for child in path.rglob("*"):
        if child.is_file():
            archive.write(child, f"{arc_prefix}{child.relative_to(path)}")


def command_export(args: argparse.Namespace) -> None:
    ui.title("HyperBot - Export")
    require_command("docker")
    values = ensure_env(prefer_default=True)
    env = build_runtime_env(values)

    export_dir = ROOT / "Exports"
    export_dir.mkdir(parents=True, exist_ok=True)
    timestamp = dt.datetime.now().strftime("%Y%m%d-%H%M%S")
    export_path = Path(args.output) if args.output else export_dir / f"hyperbot-instance-{timestamp}.zip"
    if not export_path.is_absolute():
        export_path = ROOT / export_path
    export_path.parent.mkdir(parents=True, exist_ok=True)

    ui.step("Preparing the database for export")
    docker_compose("up", "-d", "--remove-orphans", "postgresql", "redis", env=env)
    wait_for_postgresql()
    backup_path = backup_database()

    manifest = {
        "createdAt": dt.datetime.now(dt.timezone.utc).isoformat(),
        "repository": REPOSITORY_URL,
        "dashboardPort": values.get("APP_HOST_PORT"),
        "includesSecrets": True,
        "notes": "Import this export into a compatible HyperBot instance.",
    }

    ui.step(f"Creating {export_path}")
    with zipfile.ZipFile(export_path, "w", zipfile.ZIP_DEFLATED) as archive:
        add_path_to_zip(archive, ROOT / "Plugins", "Plugins/")
        if ENV_FILE.exists():
            archive.write(ENV_FILE, ".env")
        if backup_path is not None:
            archive.write(backup_path, f"Backups/PostgreSQL/{backup_path.name}")
            archive.write(ROOT / "Backups" / "PostgreSQL" / "hyperbot-latest.dump", "Backups/PostgreSQL/hyperbot-latest.dump")
        archive.writestr("manifest.json", json.dumps(manifest, indent=2))

    ui.ok(f"Export created: {export_path}")
    ui.warn("The export contains .env and therefore secrets. Keep this file private.")


def backup_plugins_for_update(timestamp: str) -> Path:
    plugin_backup = ROOT / "Backups" / "Updates" / f"Plugins-{timestamp}"
    plugin_backup.parent.mkdir(parents=True, exist_ok=True)
    if (ROOT / "Plugins").exists():
        shutil.copytree(ROOT / "Plugins", plugin_backup)
        ui.ok(f"Plugins backed up to {plugin_backup}")
    return plugin_backup


def backup_source_for_update(timestamp: str) -> Path:
    source_backup = ROOT / "Backups" / "Updates" / f"Source-{timestamp}"
    source_backup.mkdir(parents=True, exist_ok=True)

    for child in ROOT.iterdir():
        if child.name in UPDATE_SOURCE_BACKUP_EXCLUDES:
            continue

        target = source_backup / child.name
        if child.is_dir():
            shutil.copytree(child, target, ignore=shutil.ignore_patterns(*UPDATE_SOURCE_BACKUP_EXCLUDES))
        elif child.is_file():
            shutil.copy2(child, target)

    ui.ok(f"Current source backed up to {source_backup}")
    return source_backup


def restore_missing_plugins(plugin_backup: Path) -> int:
    restored = 0
    plugins_dir = ROOT / "Plugins"
    plugins_dir.mkdir(exist_ok=True)
    for backup_child in plugin_backup.iterdir() if plugin_backup.exists() else []:
        target = plugins_dir / backup_child.name
        if not target.exists():
            shutil.copytree(backup_child, target)
            restored += 1
    return restored


def git_has_head_commit() -> bool:
    return run(["git", "rev-parse", "--verify", "HEAD"], check=False, capture=True).returncode == 0


def ensure_origin_remote() -> None:
    remotes = run(["git", "remote"], check=False, capture=True)
    if "origin" in (remotes.stdout or "").splitlines():
        run(["git", "remote", "set-url", "origin", REPOSITORY_URL])
    else:
        run(["git", "remote", "add", "origin", REPOSITORY_URL])


def resolve_remote_update_branch(preferred_branch: str | None = None) -> str:
    candidates: list[str] = []
    if preferred_branch:
        candidates.append(preferred_branch)

    remote_head = run(["git", "ls-remote", "--symref", "origin", "HEAD"], check=False, capture=True)
    if remote_head.returncode == 0:
        for line in (remote_head.stdout or "").splitlines():
            parts = line.split()
            branch_prefix = "refs/heads/"
            if len(parts) >= 2 and parts[0] == "ref:" and parts[1].startswith(branch_prefix):
                candidates.append(parts[1][len(branch_prefix):])
                break

    candidates.extend(UPDATE_BRANCH_CANDIDATES)

    seen: set[str] = set()
    for branch in candidates:
        if not branch or branch in seen:
            continue
        seen.add(branch)
        remote_branch = run(["git", "ls-remote", "--heads", "origin", branch], check=False, capture=True)
        if remote_branch.returncode == 0 and (remote_branch.stdout or "").strip():
            return branch

    raise HyperBotError("Could not find an update branch on GitHub. Tried: " + ", ".join(seen))


def convert_unversioned_installation_to_git(timestamp: str, had_git_directory: bool) -> None:
    if had_git_directory:
        ui.warn("A .git folder exists, but it has no commit yet. Continuing ZIP conversion.")
    else:
        ui.warn("No .git folder found. This looks like a GitHub ZIP installation.")
    backup_source_for_update(timestamp)
    if not had_git_directory:
        run(["git", "init"])
    ensure_origin_remote()
    branch = resolve_remote_update_branch()
    run(["git", "fetch", "--depth", "1", "origin", branch])
    run(["git", "symbolic-ref", "HEAD", f"refs/heads/{branch}"])
    run(["git", "reset", "--hard", f"origin/{branch}"])
    ui.ok("ZIP installation converted to a Git repository.")


def command_update(args: argparse.Namespace) -> None:
    ui.title("HyperBot - Update")
    require_command("git")

    timestamp = dt.datetime.now().strftime("%Y%m%d-%H%M%S")
    plugin_backup = backup_plugins_for_update(timestamp)
    has_git_directory = (ROOT / ".git").exists()

    if not has_git_directory or not git_has_head_commit():
        convert_unversioned_installation_to_git(timestamp, has_git_directory)
        restored = restore_missing_plugins(plugin_backup)
        ui.ok("HyperBot code updated.")
        if restored:
            ui.ok(f"{restored} local plugin(s) restored.")
        ui.warn("Official files, including official plugins, were replaced by the GitHub version. Local copies are in Backups/Updates/.")
        ui.warn("Run `start` again to rebuild the Docker image with the new version.")
        return

    tracked = run(["git", "status", "--porcelain", "--untracked-files=no"], capture=True)
    if tracked.stdout and not args.allow_dirty:
        raise HyperBotError(
            "The repository has tracked local changes. "
            "Commit/stash those changes or rerun with --allow-dirty."
        )

    ensure_origin_remote()
    current_branch = run(["git", "branch", "--show-current"], capture=True).stdout.strip()
    branch = resolve_remote_update_branch(current_branch)
    run(["git", "fetch", "origin", branch])
    run(["git", "pull", "--ff-only", "origin", branch])

    restored = restore_missing_plugins(plugin_backup)

    ui.ok("HyperBot code updated.")
    if restored:
        ui.ok(f"{restored} local plugin(s) restored.")
    ui.warn("Run `start` again to rebuild the Docker image with the new version.")


def command_menu(_: argparse.Namespace) -> None:
    while True:
        ui.title("HyperBot CLI")
        print("1. Create/configure and start")
        print("2. Start")
        print("3. Stop")
        print("4. Configure")
        print("5. Export")
        print("6. Update from GitHub")
        print("7. Status")
        print("8. Logs")
        print("0. Quit")
        choice = input("\nChoice: ").strip()
        if choice == "1":
            command_create(argparse.Namespace(port=None, no_start=False, logs=True))
        elif choice == "2":
            command_start(argparse.Namespace(port=None, exact_port=False, no_backup=False, logs=True))
        elif choice == "3":
            command_stop(argparse.Namespace(down=False))
        elif choice == "4":
            command_configure(
                argparse.Namespace(
                    port=None,
                    host_bind=None,
                    super_admins=None,
                    registration=None,
                    tenor_key=None,
                    interactive=True,
                )
            )
        elif choice == "5":
            command_export(argparse.Namespace(output=None))
        elif choice == "6":
            command_update(argparse.Namespace(allow_dirty=False))
        elif choice == "7":
            command_status(argparse.Namespace())
        elif choice == "8":
            command_logs(argparse.Namespace(follow=True))
        elif choice == "0":
            return
        else:
            ui.warn("Invalid choice.")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="hyperbot",
        description="Cross-platform CLI to create, start, export, update, and configure HyperBot.",
    )
    subparsers = parser.add_subparsers(dest="command")

    create = subparsers.add_parser("create", help="Creates/configures a HyperBot instance and starts it.")
    create.add_argument("--port", help="Requested web port. Defaults to 3000 when available.")
    create.add_argument("--no-start", action="store_true", help="Only configures the instance.")
    create.add_argument("--logs", action="store_true", help="Follows logs after startup.")
    create.set_defaults(func=command_create)

    start = subparsers.add_parser("start", help="Builds and starts HyperBot in Docker production mode.")
    start.add_argument("--port", help="Forces the web port before startup.")
    start.add_argument("--exact-port", action="store_true", help="Fails if the requested port is already in use.")
    start.add_argument("--no-backup", action="store_true", help="Skips the PostgreSQL backup before startup.")
    start.add_argument("--logs", action="store_true", help="Follows logs after startup.")
    start.set_defaults(func=command_start)

    stop = subparsers.add_parser("stop", help="Stops HyperBot.")
    stop.add_argument("--down", action="store_true", help="Uses docker compose down instead of stop.")
    stop.set_defaults(func=command_stop)

    status = subparsers.add_parser("status", help="Shows containers and the dashboard URL.")
    status.set_defaults(func=command_status)

    logs = subparsers.add_parser("logs", help="Shows application logs.")
    logs.add_argument("-f", "--follow", action="store_true", help="Follows logs continuously.")
    logs.set_defaults(func=command_logs)

    configure = subparsers.add_parser("configure", help="Quickly updates .env.")
    configure.add_argument("--port", help="Exact web port.")
    configure.add_argument("--host-bind", help="Web bind address, for example 127.0.0.1 or 0.0.0.0.")
    configure.add_argument("--super-admins", help="Comma-separated Discord super-admin IDs.")
    configure.add_argument("--registration", action=argparse.BooleanOptionalAction, help="Enables/disables public registration.")
    configure.add_argument("--tenor-key", help="Tenor API key for EmojiAdder.")
    configure.add_argument("-i", "--interactive", action="store_true", help="Interactive configuration assistant.")
    configure.set_defaults(func=command_configure)

    export = subparsers.add_parser("export", help="Exports .env, plugins, and a PostgreSQL backup.")
    export.add_argument("-o", "--output", help="Path of the zip file to create.")
    export.set_defaults(func=command_export)

    update = subparsers.add_parser("update", help="Updates from GitHub while keeping local instance data and plugin backups.")
    update.add_argument("--allow-dirty", action="store_true", help="Allows a repository with modified tracked files.")
    update.set_defaults(func=command_update)

    menu = subparsers.add_parser("menu", help="Opens the interactive menu.")
    menu.set_defaults(func=command_menu)
    return parser


def normalize_chained_command(segment: list[str]) -> list[str]:
    normalized = list(segment)

    if len(normalized) >= 2 and Path(normalized[0]).name in {"sh", "bash", "dash"} and Path(normalized[1]).name in {"HyperBot.sh", "HyperBot.bat"}:
        normalized = normalized[2:]

    if normalized and Path(normalized[0]).name in {"HyperBot.sh", "HyperBot.bat", "hyperbot"}:
        normalized = normalized[1:]

    return normalized


def split_chained_commands(argv: list[str]) -> list[list[str]] | None:
    if "&&" not in argv:
        return None

    commands: list[list[str]] = [[]]
    for token in argv:
        if token == "&&":
            commands.append([])
        else:
            commands[-1].append(token)

    normalized = [normalize_chained_command(command) for command in commands]
    if any(not command for command in normalized):
        raise HyperBotError("Invalid chained command. Use: sh HyperBot.sh start && sh HyperBot.sh logs -f")

    return normalized


def run_chained_commands(commands: list[list[str]]) -> int:
    exit_code = 0
    for command in commands:
        exit_code = main(command)
        if exit_code != 0:
            return exit_code
    return exit_code


def main(argv: list[str] | None = None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    try:
        chained_commands = split_chained_commands(argv)
        if chained_commands is not None:
            return run_chained_commands(chained_commands)
    except HyperBotError as exc:
        ui.error(str(exc))
        return 1

    parser = build_parser()
    args = parser.parse_args(argv)
    if not hasattr(args, "func"):
        args.func = command_menu

    try:
        args.func(args)
        return 0
    except KeyboardInterrupt:
        print()
        ui.warn("Interrupted.")
        return 130
    except HyperBotError as exc:
        ui.error(str(exc))
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
